name: pull-request

on:
  pull_request:
    branches: [main]

jobs:
  test:
    uses: guslen/test-semantic-release-config/.github/workflows/test.yml@main
    with:
      codeCoverageToken: ${{ secrets.CODECOV_TOKEN }}
